name: sil_fcm
description: A wrapper package for setting up and consuming cloud notifications from firebase
version: 0.0.1
author: dmwangi@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_dart_utils

environment:  
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"


dependencies:
  firebase_core: "^1.2.1"
  firebase_messaging: "^10.0.1" 
  flutter:
    sdk: flutter   
  flutter_local_notifications: ^5.0.0+4
  rxdart: ^0.27.1

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.3 
  mockito: ^5.0.10
  test:
  test_api: '>=0.2.19'

  

flutter:
