name: sil_fcm
description: A wrapper package for setting up and consuming cloud notifications from firebase
version: 0.0.1
author: dmwangi@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_dart_utils

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^1.4.4+1
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  

flutter:
