name: sil_fcm
description: A wrapper package for setting up and consuming cloud notifications from firebase
version: 0.0.1
author: dmwangi@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_dart_utils

environment:  
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"


dependencies:
  firebase_core: "^1.0.1"
  firebase_messaging: "^9.0.0" 
  flutter:
    sdk: flutter   
  flutter_local_notifications: ^5.0.0-nullsafety.1
  rxdart: ^0.26.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  lint: ^1.0.0 
  mockito: ^5.0.3  
  test:
  test_api: '>=0.2.19'

  

flutter:
