name: dart_fcm
description: A wrapper package for setting up and consuming cloud notifications from firebase
version: 0.0.20
homepage: https://github.com/savannahghi/dart_fcm
repository: https://github.com/savannahghi/dart_fcm
issue_tracker: https://github.com/savannahghi/dart_fcm/issues
documentation: https://github.com/savannahghi/dart_fcm/doc

environment:  
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"


dependencies:
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2 
  flutter:
    sdk: flutter   
  flutter_local_notifications: ^5.0.0+4
  rxdart: ^0.27.1

dev_dependencies:
  build_runner: ^2.0.4
  firebase_messaging_platform_interface: ^3.0.2
  flutter_local_notifications_platform_interface: ^3.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.5.3 
  mockito: ^5.0.10
  test:
  test_api: '>=0.2.19'
  timezone: ^0.7.0

  
flutter:
